name: rive_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_tilt: ^3.0.6
  rive: ^0.13.7
  flutter_svg: ^2.0.0
  google_maps_flutter: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rive/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:

    - family: LamaSans
      fonts:
      - asset: assets/fonts/LamaSans-Black.otf
        weight: 900
      - asset: assets/fonts/LamaSans-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/LamaSans-Bold.otf
        weight: 700
      - asset: assets/fonts/LamaSans-SemiBold.otf
        weight: 600
      - asset: assets/fonts/LamaSans-Medium.otf
        weight: 500
      - asset: assets/fonts/LamaSans-Regular.otf
        weight: 400
      - asset: assets/fonts/LamaSans-Light.otf
        weight: 300
      - asset: assets/fonts/LamaSans-ExtraLight.otf
        weight: 200
      - asset: assets/fonts/LamaSans-Thin.otf
        weight: 100
      - asset: assets/fonts/LamaSans-BlackItalic.otf
        weight: 900
        style: italic
      - asset: assets/fonts/LamaSans-ExtraBoldItalic.otf
        weight: 800
        style: italic
      - asset: assets/fonts/LamaSans-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/LamaSans-SemiBoldItalic.otf
        weight: 600
        style: italic
      - asset: assets/fonts/LamaSans-MediumItalic.otf
        weight: 500
        style: italic
      - asset: assets/fonts/LamaSans-RegularItalic.otf
        weight: 400
        style: italic
      - asset: assets/fonts/LamaSans-LightItalic.otf
        weight: 300
        style: italic
      - asset: assets/fonts/LamaSans-ExtraLightItalic.otf
        weight: 200
        style: italic
      - asset: assets/fonts/LamaSans-ThinItalic.otf
        weight: 100
        style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

